image:
  #repository: jorinvo/prometheus-pushgateway-cleaner
  repository: ghcr.io/code-tool/helm-charts/prometheus-pushgateway-cleaner
  tag: 0.5.1
  pullPolicy: IfNotPresent
cronSchedule: "*/5 * * * *"
metricUrl: "http://pushgateway-prometheus-pushgateway:9091/metrics"
nodeSelector: {}
tolerations: []
