apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik-outpost.fullname" . }}
  labels:
    {{- include "authentik-outpost.labels" . | nindent 4 }}
type: Opaque
data:
  AUTHENTIK_HOST: {{ .Values.authentik.host | b64enc | quote }}
  AUTHENTIK_TOKEN: {{ .Values.authentik.token | b64enc | quote }}
  AUTHENTIK_INSECURE: {{.Values.authentik.insecure | toString | b64enc | quote }}